language: python

python:
  - "2.7"

install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - travis_retry conda create --yes -n TEST $CONDA --file ./requirements/development.txt
    - source activate TEST

script:
  - flake8 . --ignore E501
  - time python blockbuster.py test-data/mbtest.bed > out.tmp
  - diff test-data/mbtest_output.txt out.tmp
  - python diff_bboutput.py test-data/mbtest_coutput.tab out.tmp


